---
- include: provision.yml
  vars:
    Cluster: elasticsearch-elk
    keypair: deployment
    instance_type: t2.micro
    root_ebs_size: 8
    zone: 'us-west-1a'
    security_group_rules_ingress:
    - proto: tcp
      from_port: 9200
      to_port: 9400
      cidr_ip: 10.0.0.0/16
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 10.0.0.0/16
    subnet_cidr: '10.0.112.0/24'
    elb_listeners:
      - protocol: tcp # options are http, https, ssl, tcp
        load_balancer_port: 9200
        instance_port: 9200
    elb_health_check:
      ping_protocol: tcp
      ping_port: 9200
      response_timeout: 5 # seconds
      interval: 30 # seconds
      unhealthy_threshold: 2
      healthy_threshold: 10
- name: Configure elasticsearach
  hosts: launched
  become: True
  gather_facts: True
  vars:
    ELASTICSEARCH_HEAP_SIZE: "{{ (ansible_memtotal_mb / 2) | int }}m"
    ELASTICSEARCH_CLUSTER_NAME: "{{ Deployment }}-{{ Cluster }}"
    Number: 1
    Cluster: elasticsearch-elk
    Deployment: "{{ Deployment }}"
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
  roles:
    - common
    - oraclejdk
    - elasticsearch
- include: rotate.yml
  vars:
    Cluster: elasticsearch-elk
