- name: Deploy Analytics Insights
  hosts: ~tag_Name_{{ machine }}_{{ env }}
  become: True
  gather_facts: True
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/insights.yml"
  vars:
    COMMON_ENABLE_DATADOG: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
  roles:
    - role: nginx
      nginx_sites:
        - insights
    - insights
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
