#!/usr/bin/env ansible-playbook
---
- include: provision.yml
  vars:
    Cluster: logstash
    keypair: deployment
    instance_type: t2.micro
    root_ebs_size: 8
    zone: 'us-west-1a'
    subnet_cidr: '10.0.111.0/24'
    security_group_rules_ingress:
    - proto: tcp
      from_port: 5044
      to_port: 5044
      cidr_ip: 10.0.0.0/16
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 10.0.0.0/16
    elb_listeners:
      - protocol: tcp # options are http, https, ssl, tcp
        load_balancer_port: 5044
        instance_port: 5044
    elb_health_check:
      ping_protocol: tcp
      ping_port: 5044
      response_timeout: 5 # seconds
      interval: 30 # seconds
      unhealthy_threshold: 2
      healthy_threshold: 10
- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  vars:
    # take in number of mega bytes, will scale it properly 
    ELASTICSEARCH_HEAP_SIZE: "{{ (ansible_memtotal_mb / 2) | int }}m"
    LOGSTASH_ELASTICSEARCH_HOST: "elasticsearch-elk.{{ Deployment }}.vpc"
    Number: 1
    Cluster: logstash
    Deployment: "{{ Deployment }}"
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
  roles:
    - common
    - oraclejdk
    - logstash
- include: rotate.yml
  vars:
    Cluster: logstash
