---
KIBANA_SERVER_NAME: "192.168.33.10"
KIBANA_NGINX_PORT: 80
KIBANA_SSL_NGINX_PORT: 443
KIBANA_ENABLE_SSL: False
KIBANA_ELASTICSEARCH_HOST: localhost
KIBANA_ELASTICSEARCH_PORT: 9200

kibana_app_dir: /edx/app/kibana
kibana_version: 3.0.0
kibana_file: "kibana-{{ kibana_version }}.tar.gz"
kibana_url: "https://download.elastic.co/kibana/kibana/{{ kibana_file }}"
