- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    EDXAPP_SETTINGS: devstack
    migrate_db: 'yes'
    openid_workaround: true
    devstack: true
    disable_edx_services: true
    mongo_enable_journal: false
    EDXAPP_NO_PREREQ_INSTALL: 0
    COMMON_MOTD_TEMPLATE: 'devstack_motd.tail.j2'
    COMMON_SSH_PASSWORD_AUTH: "yes"
    EDXAPP_LMS_BASE: 127.0.0.1:8000
    EDXAPP_OAUTH_ENFORCE_SECURE: false
    EDXAPP_LMS_BASE_SCHEME: http
    edxapp_use_custom_theme: true
    edxapp_theme_name: 'lagunita'
    edxapp_theme_source_repo: 'https://github.com/Stanford-Online/lagunita-theme.git'
    ENABLE_ELK: true
    configuration_version: master
  roles:
    - edx_ansible
    - mysql
    - edxlocal
    - mongo
    - edxapp
    - oraclejdk
    - elasticsearch
    - forum
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - role: notifier
      NOTIFIER_DIGEST_TASK_INTERVAL: "5"
    - browsers
    - browsermob-proxy
    - local_dev
    - demo
    - oauth_client_setup
    - role: logstash
      when: ENABLE_ELK
    - role: nginx
      nginx_sites:
        - kibana
      when: ENABLE_ELK
    - role: kibana
      when: ENABLE_ELK
    - role: filebeat
      when: ENABLE_ELK
